### ISSUE TITLE
NameError: name 'adafruit_ccs811' is not defined

### ISSUE THREAD

**Issue by bphermansson** [adafruit/Adafruit_CircuitPython_CCS811#14]
I have put the CircuitPython bundle in the lib folder of my ItsyBitsy M0 Express. In the bundle theres a driver for the CCS811. I then try the following code:

```
import busio
import adafruit_CCS811
from board import *
i2c_bus = busio.I2C(SCL, SDA)
ccs =  adafruit_ccs811.CCS811(i2c_bus)
```

But I get an error:

```
File "code.py", line 5, in <module>
NameError: name 'adafruit_ccs811' is not defined
```

Why?

**Comment by deshipu** [comment]
It's `adafruit_CCS811` not `adafruit_ccs811` -- capitalization matters.

**Comment by deshipu** [comment]
Then again, all other libraries use lowercase names, so we should probably fix that.

**Comment by deshipu** [comment]
Try this instead:
```python
import busio
import adafruit_ccs811
from board import *
i2c_bus = busio.I2C(SCL, SDA)
ccs =  adafruit_ccs811.CCS811(i2c_bus)
```

**Comment by tannewt** [comment]
@bphermansson Please reopen if that doesn't help.

**Comment by bphermansson** [comment]
That works but gives another problem, my CCS811 is found at 0x5b, nor 0x5a, so the code fails anyway.

**Comment by deshipu** [comment]
Then you have to specify the I²C address:

```python
ccs = adafruit_ccs811.CCS811(i2c_bus, address=0x5b)
```

**Comment by bphermansson** [comment]
`ccs =  adafruit_ccs811.CCS811(i2c_bus, address=0x5b)`

> File "code.py", line 5, in <module>
> TypeError: unexpected keyword argument 'address'

**Comment by deshipu** [comment]
Sorry, they used "addr" for some reason.

**Comment by bphermansson** [comment]
Ok thanks for a quick answer, finally it works!
