### ISSUE TITLE
Check up on setEnvironmentalData() pull request from Adafruit_CCS811_python

### ISSUE THREAD

**Issue by brennen** [adafruit/Adafruit_CircuitPython_CCS811#25]
We had a pull request over there from @Blu-Eagle that should probably be evaluated with this version of the code:

https://github.com/adafruit/Adafruit_CCS811_python/pull/2

**Comment by ladyada** [comment]
@deanm1278 we archived the python repo, so take a look if this PR is relevant here!

**Comment by kattni** [comment]
@ladyada Who should we have look into this? Thanks!

**Comment by ladyada** [comment]
might be a good one for carter to check out - no rush on it :)

**Comment by kattni** [comment]
@caternuson No rush on this. If you get a chance, please look into it. Thanks!

**Comment by caternuson** [comment]
Issue seems real. Reading datasheet and comparing to code, I came to same conclusion and ended up with a fix that is equivalent to the other PR. Not sure what the original code was trying to do. This is a pretty straight forward register write.

Update submitted in #26

**Comment by caternuson** [comment]
OK to close? No rush.

...or is there?
![2112](https://user-images.githubusercontent.com/8755041/50019461-9b8a4c80-ff87-11e8-9d72-93c37b68294e.jpg)

**Comment by caternuson** [comment]
Closing Stage Left
