### ISSUE TITLE
Cannot have more bits than fit in a single byte

### ISSUE THREAD

**Issue by Nicell** [adafruit/Adafruit_CircuitPython_CCS811#28]
When running `import adafruit_ccs811` using `python3` I receive the following error on my Raspberry Pi Zero

```
traceback (most recent call last):
  File "main.py", line 7, in <module>
    import adafruit_ccs811
  File "/usr/local/lib/python3.5/dist-packages/adafruit_ccs811.py", line 76, in <module>
    class CCS811:
  File "/usr/local/lib/python3.5/dist-packages/adafruit_ccs811.py", line 90, in CCS811
    hw_id = i2c_bits.ROBits(8, 0x20, 0)
  File "/usr/local/lib/python3.5/dist-packages/adafruit_register/i2c_bits.py", line 53, in __init__
    raise ValueError("Cannot have more bits than fit in a single byte")
ValueError: Cannot have more bits than fit in a single byte
```

Not super familiar with CircuitPython, so I'm not sure what's wrong.

**Comment by granholm** [comment]
I got the same error. Been trying the exact same thing, getting the ccs811 to work on a Pi Zero.

**Comment by kattni** [comment]
This is due to a recent update to the `register` library. We will look into resolving this. Thank you for reporting it!

**Comment by ladyada** [comment]
i found the error - will be fixed on next release of `register`

**Comment by kattni** [comment]
Hello! Please update `register` to the latest release. I have tested it and it works successfully. Thanks!

**Comment by oshadmon** [comment]
Hello @kattni & @ladyada, 

First off on behalf of Nicell thank you for the quick reply! 
I too have encountered this error on Raspberry PI, and am wondering how can I resolve it in the mean time? 

Thanks, 
Ori 

Steps to repo: 
1. Install adafruit-circuitpython-ccs811 (success) 
`sudo pip3 install adafruit-circuitpython-ccs811`
2. In python3.53 `import adafruit_ccs811` 

Expect: success 
Actual: 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/adafruit_ccs811.py", line 76, in <module>
    class CCS811:
  File "/usr/local/lib/python3.5/dist-packages/adafruit_ccs811.py", line 90, in CCS811
    hw_id = i2c_bits.ROBits(8, 0x20, 0)
  File "/usr/local/lib/python3.5/dist-packages/adafruit_register/i2c_bits.py", line 53, in __init__
    raise ValueError("Cannot have more bits than fit in a single byte")
ValueError: Cannot have more bits than fit in a single byte
>>> import adafruit_CCS811
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'adafruit_CCS811'
```

**Comment by ladyada** [comment]
something like `sudo pip3 install --upgrade adafruit-circuitpython-register`
im not in front of a linux terminal, you need to upgrade the library, so check pip3 dox

**Comment by dhalbert** [comment]
Try it without the `sudo` first.

**Comment by dhalbert** [comment]
ok, never mind, if you already used `sudo` for the initial install, then it's better to be consistent, but in general it's better to use `pip3` without `sudo` if you can, so that you don't inadvertently occlude system libraries.

**Comment by Nicell** [comment]
After running `sudo pip3 install --upgrade adafruit-circuitpython-register`, it states that `register` is already up to date. The pip site also shows that the package was [last updated on the 15th](https://pypi.org/project/adafruit-circuitpython-register/). It doesn't look like the new fix is available yet via pip3.

**Comment by kattni** [comment]
Apologies. It looks like the Travis build failed before deploying the fix to PyPI. I'm looking into it now.

**Comment by kattni** [comment]
The fail was a glitch. It passed on restart. @Nicell Please try again.

**Comment by Nicell** [comment]
@kattni kept saying up to date, but finally on my 5th or so attempt and reinstalling a few times it had picked up the new version. Everything seems to work now. Thank you for your help!
