### ISSUE TITLE
CircuitPython 2.0 rc2 throws RunTimeError in Adafruit_CCS811.py

### ISSUE THREAD

**Issue by hukuzatuna** [adafruit/Adafruit_CircuitPython_CCS811#3]
I am testing CircuitPython 2.0 and found this problem:

code.py output:
Traceback (most recent call last):
  File "code.py", line 50, in <module>
  File "/lib/Adafruit_CCS811.py", line 116, in __init__
  File "libraries/helpers/bus_device/adafruit_bus_device/i2c_device.py", line 94, in write
RuntimeError: Function requires lock.

**Comment by ladyada** [comment]
@deanm1278 @tannewt looks like the i2c lock implementation was added :) do either of you want to try adding the try lock?

**Comment by jerryneedell** [comment]
This appears to be working now. I am able to access a CCS811 with the latest master and Adafruit_CircuitPython_CCS811 library.

**Comment by tannewt** [comment]
Closing since it works for @jerryneedell .
