### ISSUE TITLE
Check firmware version for temperature support?

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_CCS811#33]
Not really an issue, just a potential option.

Currently the `temperature` property is marked as deprecated to deal with the feature being removed from the chip. See #30 and #32.

Another approach might be to query the version information registers:
![image](https://user-images.githubusercontent.com/8755041/62060328-c43f1980-b1d9-11e9-9295-3b2c7aba19c1.png)
and then raise exception if a newer rev:
```python
if version > THE_LAST_VERSION_THAT_HAD_TEMPERATURE:
    raise RuntimeError("Feature not supported for this chip version")
```

**Comment by ladyada** [comment]
v2 is what dropped it, but i dont think its wise to use the temp sensor at all...then that code wouldn't be usable by others

**Comment by caternuson** [comment]
okie dokie. works for me.
