### ISSUE TITLE
Dead link in README.rst

### ISSUE THREAD

**Issue by linusg** [adafruit/Adafruit_CircuitPython_CCS811#37]
This link returns a 404: https://learn.adafruit.com/ccs811-air-quality-sensor/circuit-python-example

https://github.com/adafruit/Adafruit_CircuitPython_CCS811/blob/975a23d9ffe510dc35417e8007ef5548d2c8771d/README.rst#L59

**Comment by caternuson** [comment]
Thanks for spotting that. Looks like that should be changed to:
https://learn.adafruit.com/adafruit-ccs811-air-quality-sensor/python-circuitpython
Do you want to PR a fix?

**Comment by linusg** [comment]
>  Do you want to PR a fix?

Sure thing. https://github.com/adafruit/Adafruit_CircuitPython_CCS811/pull/38

**Comment by caternuson** [comment]
Awesome. Thanks!
